from __future__ import annotations
from typing import Literal, Optional, TypedDict
from pydantic import BaseModel, Field


class ContextChunk(BaseModel):
    title: str
    text: str


class QAExample(BaseModel):
    qid: str
    difficulty: Literal["easy", "medium", "hard"]
    question: str
    gold_answer: str
    context: list[ContextChunk]


class JudgeResult(BaseModel):
    """Evaluation result from the Evaluator/Judge LLM."""
    score: int = Field(
        ...,
        ge=0,
        le=1,
        description="Binary correctness score: 1 if the predicted answer is correct, 0 otherwise.",
    )
    reason: str = Field(
        ...,
        description="A concise explanation of why the answer is correct or incorrect, "
                    "referencing specific evidence (or its absence) from the context.",
    )


class ReflectionEntry(BaseModel):
    """A single reflection step generated by the Reflector LLM."""
    attempt_id: int = Field(
        ...,
        description="The 1-based index of the failed attempt that triggered this reflection.",
    )
    failure_reason: str = Field(
        ...,
        description="A precise description of why the previous answer was wrong, "
                    "derived from the evaluator's reasoning.",
    )
    lesson: str = Field(
        ...,
        description="The key insight or principle learned from this failure that "
                    "should prevent the same mistake in the next attempt.",
    )
    next_strategy: str = Field(
        ...,
        description="A concrete, actionable plan for how the Actor should approach "
                    "the next attempt differently to arrive at the correct answer.",
    )


class AttemptTrace(BaseModel):
    attempt_id: int
    answer: str
    score: int
    reason: str
    reflection: Optional[ReflectionEntry] = None
    token_estimate: int = 0
    latency_ms: int = 0


class RunRecord(BaseModel):
    qid: str
    question: str
    gold_answer: str
    agent_type: Literal["react", "reflexion"]
    predicted_answer: str
    is_correct: bool
    attempts: int
    token_estimate: int
    latency_ms: int
    failure_mode: Literal[
        "none",
        "entity_drift",
        "incomplete_multi_hop",
        "wrong_final_answer",
        "looping",
        "reflection_overfit",
    ]
    reflections: list[ReflectionEntry] = Field(default_factory=list)
    traces: list[AttemptTrace] = Field(default_factory=list)


class ReportPayload(BaseModel):
    meta: dict
    summary: dict
    failure_modes: dict
    examples: list[dict]
    extensions: list[str]
    discussion: str


class ReflexionState(TypedDict):
    question: str
    context: list[str]
    trajectory: list[str]
    reflection_memory: list[str]
    attempt_count: int
    success: bool
    final_answer: str
